"""v2.4.0

Revision ID: 1983d6b6e2c1
Revises: 346f4a91caf3
Create Date: 2024-04-12 08:43:03.779935

"""
import os
import sys

from alembic import op
import sqlalchemy as sa

from alembic_postgresql_enum import ColumnType
from alembic_postgresql_enum import TableReference
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

PROJECT_PATH = os.getcwd()
SOURCE_PATH = os.path.join(
    PROJECT_PATH, "src"
)
sys.path.append(SOURCE_PATH)

# revision identifiers, used by Alembic.
revision = '1983d6b6e2c1'
down_revision = '346f4a91caf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bp_kennzeichnung',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('zweckbestimmung',
                              sa.Enum('Naturgewalten', 'Abbauflaeche', 'AeussereEinwirkungen',
                                      'SchadstoffBelastBoden', 'LaermBelastung', 'Bergbau', 'Bodenordnung',
                                      'Vorhabensgebiet', 'AndereGesetzlVorschriften',
                                      name='xp_zweckbestimmungkennzeichnung'),
                              nullable=True),
                    sa.Column('istVerdachtsflaeche', sa.Boolean(), nullable=True),
                    sa.Column('nummer', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['bp_objekt.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM xp_objekt CASCADE WHERE type in ('bp_kennzeichnung');")

    op.drop_table('bp_kennzeichnung')
    op.execute("DROP TYPE xp_zweckbestimmungkennzeichnung;")
    # ### end Alembic commands ###
