"""v2.13.0

Revision ID: 2b1452b49cc5
Revises: 315e0f69004f
Create Date: 2026-02-02 11:26:53.233493

"""
import os
import sys

from alembic import op, context
import sqlalchemy as sa

from alembic_postgresql_enum import ColumnType
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

PROJECT_PATH = os.getcwd()
SOURCE_PATH = os.path.join(
    PROJECT_PATH, "src"
)
sys.path.append(SOURCE_PATH)


# revision identifiers, used by Alembic.
revision = '2b1452b49cc5'
down_revision = '315e0f69004f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xp_gener_attribut',
sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=True),
        sa.Column('plan_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('xp_objekt_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], ['xp_plan.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['xp_objekt_id'], ['xp_objekt.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_datum_attribut',
sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wert', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['xp_gener_attribut.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_double_attribut',
sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wert', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['xp_gener_attribut.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_integer_attribut',
sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wert', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['xp_gener_attribut.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_string_attribut',
sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wert', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['xp_gener_attribut.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_url_attribut',
sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wert', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['xp_gener_attribut.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    schutztyp_enum = postgresql.ENUM('Schutzflaeche', 'BesondereAnlagenVorkehrungen',
                                     name='xp_immissionsschutztypen', create_type=False)
    vorkehrung_enum = postgresql.ENUM('Laermschutzvorkehrung', 'FassadenMitSchallschutzmassnahmen',
                                      'Laermschutzwand', 'Laermschutzwall', 'SonstigeVorkehrung',
                                      name='xp_technvorkehrungenimmissionsschutz', create_type=False)
    wasserwirtschaft_enum = postgresql.ENUM('HochwasserRueckhaltebecken', 'Ueberschwemmgebiet',
                                            'Versickerungsflaeche', 'Entwaesserungsgraben', 'Deich',
                                            'RegenRueckhaltebecken', 'Sonstiges',
                                            name='xp_zweckbestimmungwasserwirtschaft', create_type=False)

    if not context.is_offline_mode():
        schutztyp_enum.create(op.get_bind(), checkfirst=True)
        vorkehrung_enum.create(op.get_bind(), checkfirst=True)
        wasserwirtschaft_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('fp_nutzungsbeschraenkung',
sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nutzung', sa.String(), nullable=True),
        sa.Column('typ', schutztyp_enum, nullable=True),
        sa.Column('technVorkehrung', vorkehrung_enum, nullable=True),
        sa.ForeignKeyConstraint(['id'], ['fp_objekt.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assoc_detail_vorkehrung_immissionschutz',
sa.Column('codelist_user_id', sa.UUID(), nullable=True),
        sa.Column('codelist_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['codelist_id'], ['codelist_values.id'], ),
        sa.ForeignKeyConstraint(['codelist_user_id'], ['fp_nutzungsbeschraenkung.id'], ondelete='CASCADE')
    )
    op.create_table('fp_nutzungsbeschraenkung_flaeche',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['fp_objekt.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('bp_wasserwirtschaft',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('zweckbestimmung', wasserwirtschaft_enum, nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['bp_objekt.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('assoc_detail_zweckwasserwirtschaft',
                    sa.Column('codelist_user_id', sa.UUID(), nullable=True),
                    sa.Column('codelist_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['codelist_id'], ['codelist_values.id'], ),
                    sa.ForeignKeyConstraint(['codelist_user_id'], ['bp_wasserwirtschaft.id'], ondelete='CASCADE')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xp_url_attribut')
    op.drop_table('xp_string_attribut')
    op.drop_table('xp_integer_attribut')
    op.drop_table('xp_double_attribut')
    op.drop_table('xp_datum_attribut')
    op.drop_table('xp_gener_attribut')

    op.drop_table('assoc_detail_vorkehrung_immissionschutz')
    op.drop_table('assoc_detail_zweckwasserwirtschaft')
    op.drop_table('fp_nutzungsbeschraenkung')
    op.drop_table('fp_nutzungsbeschraenkung_flaeche')
    op.drop_table('bp_wasserwirtschaft')
    op.execute("DELETE FROM xp_objekt CASCADE WHERE type in ('fp_nutzungsbeschraenkung', 'fp_nutzungsbeschraenkung_flaeche', 'bp_wasserwirtschaft');")
    # ### end Alembic commands ###
