"""v2.13.0

Revision ID: 2b1452b49cc5
Revises: 315e0f69004f
Create Date: 2026-02-02 11:26:53.233493

"""
import os
import sys

from alembic import op
import sqlalchemy as sa

from alembic_postgresql_enum import ColumnType
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

PROJECT_PATH = os.getcwd()
SOURCE_PATH = os.path.join(
    PROJECT_PATH, "src"
)
sys.path.append(SOURCE_PATH)


# revision identifiers, used by Alembic.
revision = '2b1452b49cc5'
down_revision = '315e0f69004f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xp_gener_attribut',
sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=True),
        sa.Column('plan_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('xp_objekt_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], ['xp_plan.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['xp_objekt_id'], ['xp_objekt.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_datum_attribut',
sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wert', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['xp_gener_attribut.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_double_attribut',
sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wert', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['xp_gener_attribut.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_integer_attribut',
sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wert', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['xp_gener_attribut.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_string_attribut',
sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wert', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['xp_gener_attribut.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_url_attribut',
sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wert', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['xp_gener_attribut.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xp_url_attribut')
    op.drop_table('xp_string_attribut')
    op.drop_table('xp_integer_attribut')
    op.drop_table('xp_double_attribut')
    op.drop_table('xp_datum_attribut')
    op.drop_table('xp_gener_attribut')
    # ### end Alembic commands ###
