"""v2.9.0

Revision ID: 31058f6befbd
Revises: e9b38a472653
Create Date: 2025-02-10 13:20:43.306148

"""
import os
import sys

from alembic import op
import sqlalchemy as sa

from alembic_postgresql_enum import ColumnType
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

PROJECT_PATH = os.getcwd()
SOURCE_PATH = os.path.join(
    PROJECT_PATH, "src"
)
sys.path.append(SOURCE_PATH)


# revision identifiers, used by Alembic.
revision = '31058f6befbd'
down_revision = 'e9b38a472653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TABLE xp_objekt ALTER COLUMN type TYPE varchar;")

    op.create_table('lp_biotopverbund_biotopvernetzung',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('planungsEbene', sa.ARRAY(postgresql.ENUM('Biotopverbund', 'Biotopvernetzung', name='lp_planungsebene')), nullable=True),
        sa.Column('rechtlicheSicherung', sa.Enum('Schutzerklaerung', 'PlanungsrechtlicheFestlegung', 'VertraglicheRegelung', 'Sonstiges', name='lp_rechtlichesicherung'), nullable=True),
        sa.Column('rechtlicheSicherungText', sa.String(), nullable=True),
        sa.Column('bioVerbundsystemArt', sa.Enum('Allgemein', 'OffenlandHalboffenland', 'Wald', 'Gewaesser', name='lp_bioverbundsystemart'), nullable=False),
        sa.Column('bioVStandortFeuchte', sa.Enum('Feucht', 'Mittel', 'Trocken', name='lp_biovstandortfeuchte'), nullable=True),
        sa.Column('bioVerbundsystemText', sa.String(), nullable=True),
        sa.Column('foerdermoeglichkeit', sa.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['lp_objekt.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('lp_eingriffsregelung',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('umsetzungsstand', sa.Enum('NachrichtlichUmgesetztOderAngerechnet', 'Vorschlag', 'Unbekannt', name='lp_umsetzungsstand'), nullable=False),
        sa.Column('massnahmentyp', sa.ARRAY(postgresql.ENUM('Kompensationsmassnahme', 'MassnahmeCEF', 'MassnahmeFCS', 'MassnahmeKohaerenzsicherung', 'Unbekannt', name='lp_massnahmentyp')), nullable=False),
        sa.Column('kompensationText', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['lp_objekt.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('lp_generisches_objekt',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['lp_objekt.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('lp_schutz_bestimmter_teile_von_natur_und_landschaft',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('artDerFestlegung', sa.Enum('Naturschutzgebiet', 'Nationalpark', 'Biosphaerenreservat', 'Landschaftsschutzgebiet', 'Naturpark', 'Naturdenkmal', 'GeschuetzterLandschaftsbestandteil', 'GesetzlichgeschuetztesBiotop', 'Natura2000', 'GebietGemeinschaftlicherBedeutung', 'EuropaeischesVogelschutzgebiet', 'NationalesNaturmonument', 'Sonstiges', name='lp_klassifizierungnaturschutzrecht'), nullable=False),
        sa.Column('artDerFestlegungText', sa.String(), nullable=True),
        sa.Column('rechtsstandSchG', sa.Enum('Geplant', 'Bestehend', 'Fortfallend', 'Eignung', 'Erweiterung', 'Qualifizierung', 'Sonstiges', name='lp_rechtsstandschutzgeb'), nullable=False),
        sa.Column('rechtsstandSchGText', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('nummer', sa.String(), nullable=True),
        sa.Column('gesetzlGeschBiotop', sa.Enum('Gewaesserbiotope', 'FeuchtUndNassbiotope', 'Trockenbiotope', 'Waldbiotope', 'FelsenAlpineBiotope', 'Kuestenbiotope', 'Sonstiges', name='lp_gesgeschbiotoptyp'), nullable=True),
        sa.Column('gesetzlGeschBiotopText', sa.String(), nullable=True),
        sa.Column('detailGesetzlGeschBiotopLR_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('schutzzone', sa.Enum('Schutzzone1', 'Schutzzone2', 'Schutzzone3', 'Kernzone', 'Pflegezone', 'Entwicklungszone', 'Regenerationszone', 'Sonstiges', name='lp_schutzzonennaturschutzrecht'), nullable=True),
        sa.Column('schutzzonenText', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['detailGesetzlGeschBiotopLR_id'], ['codelist_values.id'], ),
        sa.ForeignKeyConstraint(['id'], ['lp_objekt.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('lp_text_abschnitt_objekt',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['lp_objekt.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('lp_ziele_erfordernisse_massnahmen',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('artDerFestlegung', sa.ARRAY(postgresql.ENUM('Ziel', 'Erfordernis', 'Massnahme', name='lp_zemtyp')), nullable=False),
        sa.Column('freiraeume', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('foerdermoeglichkeit', sa.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['lp_objekt.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('assoc_detail_zweckgenerischeobjekte',
        sa.Column('codelist_user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('codelist_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['codelist_id'], ['codelist_values.id'], ),
        sa.ForeignKeyConstraint(['codelist_user_id'], ['lp_generisches_objekt.id'], ondelete='CASCADE')
    )

    op.create_table('lp_adressat_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('adressatArt', postgresql.ENUM('Naturschutz', 'Bauleitplanung', 'Raumordnung', 'Flurneuordnung', 'Forstwirtschaft', 'Landwirtschaft', 'Wasserwirtschaft', 'Fischereiwirtschaft', 'Jagd', 'RohstoffgewinnungUndBergbau', 'VerteidigungSicherungDerZivilbevoelkerung', 'Verkehrsplanung', 'Energiegewinnung', 'Abfallwirtschaft', 'Bodenschutz', 'KommunaleKoerperschaften', 'LandKreisverwaltung', 'Land', 'Unbekannt', 'Sonstiges', name='lp_adressatart'), nullable=False),
        sa.Column('adressatText', sa.String(), nullable=True),
        sa.Column('ziele_erfordernisse_massnahmen_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['ziele_erfordernisse_massnahmen_id'], ['lp_ziele_erfordernisse_massnahmen.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_biologische_vielfalt_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('bioVfArtFFHAnhangII', sa.Boolean(), nullable=False),
        sa.Column('ziele_erfordernisse_massnahmen_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['ziele_erfordernisse_massnahmen_id'], ['lp_ziele_erfordernisse_massnahmen.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_boden_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('bodenAuspraegung', postgresql.ENUM('Ablagerungen', 'Altablagerungsflaeche', 'Altlastenverdachtsflaeche', 'BodenFilterUndPufferfunktion', 'BodenHoheBodenfruchtbarkeit', 'BodenHoherFunktionglobalerKlimaschutz', 'BodenKulturgeschichtlicheBedeutung', 'BodenNaturgeschichtlicheBedeutung', 'BodenGeowissenschaftlicheBedeutung', 'NatuerlicheBoeedenExtremstandort', 'EhemaligerMilitaerischGenutzterStandort', 'Erosionsgefaehrdet', 'ErosionsgefaehrdetWind', 'ErosionsgefaehrdetWasser', 'Geotop', 'SelteneBodenform', 'NaturnaherBoden', 'BoedenHohesRetentionspotenzial', 'EntsiegelungOderWiederherstellungBodenfunktion', 'Sonstiges', name='lp_bodenauspraegung'), nullable=False),
        sa.Column('bodenText', sa.String(), nullable=True),
        sa.Column('ziele_erfordernisse_massnahmen_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['ziele_erfordernisse_massnahmen_id'], ['lp_ziele_erfordernisse_massnahmen.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_eingriffsregelung_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('eRFlaechenArt', postgresql.ENUM('PotenzielleFlaecheKompensation', 'Flaechenpool', 'KompensationEinzelflaeche', 'Kompensationsverzeichnis', 'Sonstiges', name='lp_erflaechenart'), nullable=False),
        sa.Column('eRFlaechenArtText', sa.String(), nullable=True),
        sa.Column('eingriffsregelung_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['eingriffsregelung_id'], ['lp_eingriffsregelung.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_erholung_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('erholungFunktionArt', postgresql.ENUM('Gruenflaechen', 'ParkanlageGruenanlage', 'Dauerkleingaerten', 'Sportplatz', 'Spielplatz', 'BadeplatzFreibad', 'Liegewiese', 'Erholungsinfrastruktur', 'Schutzhuette', 'Rastplatz', 'Informationstafel', 'FeuerstelleGrillplatz', 'Aussichtsturm', 'Aussichtspunkt', 'Angelteich', 'Modellflugplatz', 'Gleitschirmplatz', 'WildgehegeSchaugatter', 'Parkplatz', 'ZeltplatzCampingplatz', 'JugendzeltplatzEinzelcamp', 'ErholungsInfrastrukturMitBesondererBedeutung', 'WandernAllgemein', 'Wanderweg', 'Lehrpfad', 'Reitweg', 'Radweg', 'Wintersport', 'Skiabfahrt', 'Skilanglaufloipe', 'RodelbahnBobbahn', 'WassersportSchifffahrt', 'Wasserwanderweg', 'Schifffahrtsroute', 'AnlegestelleMitMotorbooten', 'AnlegestelleOhneMotorboote', 'Seilbahn', 'SesselliftSchlepplift', 'Kabinenseilbahn', 'Bildungsstaette', 'Umweltbildungsstaette', 'Museum', 'Sonstiges', name='lp_erholungfunktionen'), nullable=False),
        sa.Column('erholungFunktionText', sa.String(), nullable=True),
        sa.Column('ziele_erfordernisse_massnahmen_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['ziele_erfordernisse_massnahmen_id'], ['lp_ziele_erfordernisse_massnahmen.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_klima_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('klimaArt', postgresql.ENUM('BioklimatischeFunktion', 'Luftleitbahn', 'Frischluftbahn', 'Frischluftentstehungsgebiet', 'Kaltluftbahn', 'Kaltluftentstehungsgebiet', 'Stadtklima', 'THGSenkenKlimaschutzflaechen', 'Sonstiges', name='lp_klimaart'), nullable=False),
        sa.Column('klimaText', sa.String(), nullable=True),
        sa.Column('ziele_erfordernisse_massnahmen_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['ziele_erfordernisse_massnahmen_id'], ['lp_ziele_erfordernisse_massnahmen.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_landschaftsbild_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('landschaftsbildArt', postgresql.ENUM('KircheKlosterKapelle', 'BurgSchloss', 'Turm', 'HistorischesOrtsbild', 'Ruine', 'KulturgeschichtlichWertvollerOrtsteil', 'Aussichtspunkt', 'Aussichtsturm', 'LandschaftsgerechteEinbindung', 'LandschaftsgerechterSiedlungsrand', 'Strukturvielfalt', 'LandschaftMitHoherEigenart', 'Landschaftsachsen', 'Landschaftsraeume', 'HistorischeWaldinsel', 'Waldraender', 'Kulturlandschaft', 'HistorischeKulturlandschaft', 'Kulturlandschaftselement', 'Hohlweg', 'Gartendenkmal', 'Sonstiges', name='lp_landschaftsbildart'), nullable=False),
        sa.Column('landschaftsbildText', sa.String(), nullable=True),
        sa.Column('ziele_erfordernisse_massnahmen_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['ziele_erfordernisse_massnahmen_id'], ['lp_ziele_erfordernisse_massnahmen.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_luft_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('luftArt', postgresql.ENUM('Geruchsbelastung', 'Laermbelastung', 'LufthygienischeFktStofflBelastung', 'Staubbelastung', 'Sonstiges', name='lp_luftart'), nullable=False),
        sa.Column('luftText', sa.String(), nullable=True),
        sa.Column('ziele_erfordernisse_massnahmen_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['ziele_erfordernisse_massnahmen_id'], ['lp_ziele_erfordernisse_massnahmen.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_nutzungseinschraenkung_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('hatNutzungseinschraenkung', sa.Boolean(), nullable=False),
        sa.Column('nutzungseinschraenkungText', sa.String(), nullable=False),
        sa.Column('ziele_erfordernisse_massnahmen_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['ziele_erfordernisse_massnahmen_id'], ['lp_ziele_erfordernisse_massnahmen.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_schutzgut_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('schutzgutArt', postgresql.ENUM('AlleSchutzgueter', 'ArtenUndLebensgemeinschaften', 'Biotope', 'Boden', 'Wasser', 'Klima', 'Luft', 'Landschaftsbild', 'ErholungInNaturUndLandschaft', 'Unbekannt', 'Sonstiges', name='lp_schutzgutart'), nullable=False),
        sa.Column('schutzgutText', sa.String(), nullable=True),
        sa.Column('ziele_erfordernisse_massnahmen_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['ziele_erfordernisse_massnahmen_id'], ['lp_ziele_erfordernisse_massnahmen.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_spe_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('schutzPflegeEntwicklungTyp', sa.ARRAY(postgresql.ENUM('Schutz', 'Pflege', 'Entwicklung', 'Anlage', 'Wiederherstellung', 'Vermeidung', 'Minderung', 'Beseitigung', 'Sonstiges', name='lp_schutzpflegeentwicklung')), nullable=False),
        sa.Column('schutzPflegeEntwicklungText', sa.String(), nullable=True),
        sa.Column('ziele_erfordernisse_massnahmen_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['ziele_erfordernisse_massnahmen_id'], ['lp_ziele_erfordernisse_massnahmen.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_typ_bioverbundkomplexe',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('flaechenTypBV', postgresql.ENUM('Kernflaeche', 'Verbindungsflaeche', 'Verbindungselement', name='lp_flaechentypbv'), nullable=False),
        sa.Column('flaechentypBVSpeziell', sa.Enum('Verbindungsraeume', 'Verbundachse', 'Wildtierkorridor', 'Entwicklungsflaeche', 'Entwicklungsmassnahme', 'Vernetzungselement', 'Trittsteinbiotop', 'Sonstiges', name='lp_flaechentypbvspeziell'), nullable=True),
        sa.Column('flaechentypSpeziellText', sa.String(), nullable=True),
        sa.Column('biotopverbund_biotopvernetzung_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['biotopverbund_biotopvernetzung_id'], ['lp_biotopverbund_biotopvernetzung.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_wasser_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wasserAuspraegung', postgresql.ENUM('Hochwasserschutz', 'Ueberschwemmungsgebiet', 'Hochwasservorsorge', 'Retentionsraum', 'Polderflaeche', 'Deichrueckverlegung', 'Trinkwassergewinnung', 'Trinkwasserschutz', 'Grundwasserneubildungsgebiet', 'LaengsdurchgaengigkeitGewaesser', 'MindestwasserfuehrungGewaesser', 'Drainage', 'Entwaesserungsgraben', 'NaturnaheGewaesser', 'NaturnaheUferbereiche', 'OekologischeFunktionFliessgewaesser', 'OekologischeFunktionQuellbereich', 'OekologischeFunktionStillgewaesser', 'Gewaesserstruktur', 'Gewaesserdynamik', 'Gewaesserrandstreifen', 'Gewaesserschutzstreifen', 'Pufferzone', 'Ufergehoelze', 'FischaufstiegsOderAbstiegsanlage', 'Wehr', 'Verrohrung', 'Sohlstufe', 'Gewaesserguete', 'StoffeintraegeInGrundwasser', 'StoffeintraegeInOberflaechengewaesser', 'Versickerungsflaeche', 'Verlandungsbereiche', 'Sonstiges', name='lp_wasserauspraegung'), nullable=False),
        sa.Column('wasserText', sa.String(), nullable=True),
        sa.Column('ziele_erfordernisse_massnahmen_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['ziele_erfordernisse_massnahmen_id'], ['lp_ziele_erfordernisse_massnahmen.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_ziel_dim_nat_sch_la_pfl_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('zielDimensionTyp', postgresql.ENUM('SchutzBiologischeVielfalt', 'SchutzNaturhaushalt', 'SchutzLandschaftsbildErholungsvorsorge', 'Unbekannt', 'Sonstiges', name='lp_zieldimensiontyp'), nullable=False),
        sa.Column('zielDimensionText', sa.String(), nullable=True),
        sa.Column('ziele_erfordernisse_massnahmen_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['ziele_erfordernisse_massnahmen_id'], ['lp_ziele_erfordernisse_massnahmen.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_bio_vf_biotoptyp_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('bioVfBiotoptyp_BKompV_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('bioVfBiotoptyp_LandesKS_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('bioVf_FFH_LRT_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('bioVfBiotoptyp_Text', sa.String(), nullable=True),
        sa.Column('biologische_vielfalt_komplex_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['bioVfBiotoptyp_BKompV_id'], ['codelist_values.id'], ),
        sa.ForeignKeyConstraint(['bioVfBiotoptyp_LandesKS_id'], ['codelist_values.id'], ),
        sa.ForeignKeyConstraint(['bioVf_FFH_LRT_id'], ['codelist_values.id'], ),
        sa.ForeignKeyConstraint(['biologische_vielfalt_komplex_id'], ['lp_biologische_vielfalt_komplex.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_bio_vf_pflanzen_art_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('bioVfPflanzenArtName', sa.String(), nullable=True),
        sa.Column('bioVfPflanzenSystematik', postgresql.ENUM('Gefaesspflanze', 'MooseUndFlechten', 'Pilze', 'Sonstiges', name='lp_biovfpflanzenartsystematik'), nullable=False),
        sa.Column('bioVfPflanzenSystematikText', sa.String(), nullable=True),
        sa.Column('bioVfPflanzenRechtlicherSchutz', sa.ARRAY(postgresql.ENUM('AnhangIVFFHRL', 'Anlage1BArtSchV', 'Verantwortungsart', 'Sonstige', name='lp_biovfpflanzenartrechtlicherschutz')), nullable=True),
        sa.Column('bioVfPflanzenRechtlicherSchutzText', sa.String(), nullable=True),
        sa.Column('biologische_vielfalt_komplex_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['biologische_vielfalt_komplex_id'], ['lp_biologische_vielfalt_komplex.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_bio_vf_tiere_art_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('bioVfTierArtName', sa.String(), nullable=True),
        sa.Column('bioVfTiereSystematik', postgresql.ENUM('Grosssaeuger', 'Wolf', 'Luchs', 'Mittelsaeuger', 'Wildkatze', 'Fischotter', 'Biber', 'Marder', 'Kleinsaeuger', 'KleinsaeugerNagetiere', 'Feldhamster', 'Maeuse', 'KleinsaeugerHasenartige', 'KleinsaeugerInsektenfresser', 'Spitzmaeuse', 'KleinsaeugerFledermaeuse', 'Meeressaeuger', 'Voegel', 'Zugvoegel', 'Brutvoegel', 'Reptilien', 'Amphibien', 'Fische', 'Gliederfuesser', 'Libellen', 'Tagfalter', 'Kaefer', 'Heuschrecken', 'Spinnen', 'Krebstiere', 'Mollusken', 'Sonstiges', name='lp_biovftiereartsystematik'), nullable=False),
        sa.Column('bioVfTiereSystematikText', sa.String(), nullable=True),
        sa.Column('bioVfTierArtRechtlicherSchutz', sa.ARRAY(postgresql.ENUM('ArtAnhangIVFFHRL', 'ArtAnhangIArt4Abs2VSRL', 'ArtAnlage1BArtSchV', 'Verantwortungsart', 'Sonstige', name='lp_biovftierartrechtlicherschutz')), nullable=True),
        sa.Column('bioVfTierArtRechtlicherSchutzText', sa.String(), nullable=True),
        sa.Column('bioVfTierArtHabitatanforderung', sa.Enum('GrosserHabitatsAnspruch', 'Gebaeudebewohnend', 'Sonstige', name='lp_biovftierarthabitatanforderung'), nullable=True),
        sa.Column('bioVfTierArtHabitatanforderungText', sa.String(), nullable=True),
        sa.Column('biologische_vielfalt_komplex_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['biologische_vielfalt_komplex_id'], ['lp_biologische_vielfalt_komplex.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_biologische_vielfalt_typ_komplex',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('bioVielfaltTyp', postgresql.ENUM('Art', 'BiotopLebensraum', 'LebensstaetteArthabitat', 'Sonstiges', name='lp_biovfbestandteil'), nullable=False),
        sa.Column('bioVielfaltTypText', sa.String(), nullable=True),
        sa.Column('biologische_vielfalt_komplex_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['biologische_vielfalt_komplex_id'], ['lp_biologische_vielfalt_komplex.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # fix codelist reading by also storing keys in database
    op.add_column('codelist_values', sa.Column('key', sa.String(), nullable=True))

    # some more ppo columns
    op.add_column('xp_po', sa.Column('darstellungsprioritaet', sa.Integer(), nullable=True))
    op.add_column('xp_po', sa.Column('art', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('xp_po', sa.Column('index', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lp_biologische_vielfalt_typ_komplex')
    op.drop_table('lp_bio_vf_tiere_art_komplex')
    op.drop_table('lp_bio_vf_pflanzen_art_komplex')
    op.drop_table('lp_bio_vf_biotoptyp_komplex')
    op.drop_table('lp_ziel_dim_nat_sch_la_pfl_komplex')
    op.drop_table('lp_wasser_komplex')
    op.drop_table('lp_typ_bioverbundkomplexe')
    op.drop_table('lp_spe_komplex')
    op.drop_table('lp_schutzgut_komplex')
    op.drop_table('lp_nutzungseinschraenkung_komplex')
    op.drop_table('lp_luft_komplex')
    op.drop_table('lp_landschaftsbild_komplex')
    op.drop_table('lp_klima_komplex')
    op.drop_table('lp_erholung_komplex')
    op.drop_table('lp_eingriffsregelung_komplex')
    op.drop_table('lp_boden_komplex')
    op.drop_table('lp_biologische_vielfalt_komplex')
    op.drop_table('lp_adressat_komplex')
    op.drop_table('assoc_detail_zweckgenerischeobjekte')
    op.drop_table('lp_ziele_erfordernisse_massnahmen')
    op.drop_table('lp_text_abschnitt_objekt')
    op.drop_table('lp_schutz_bestimmter_teile_von_natur_und_landschaft')
    op.drop_table('lp_generisches_objekt')
    op.drop_table('lp_eingriffsregelung')
    op.drop_table('lp_biotopverbund_biotopvernetzung')

    op.execute("DROP TYPE lp_erflaechenart")
    op.execute("DROP TYPE lp_flaechentypbv")
    op.execute("DROP TYPE lp_planungsebene")
    op.execute("DROP TYPE lp_massnahmentyp")
    op.execute("DROP TYPE lp_flaechentypbvspeziell")
    op.execute("DROP TYPE lp_rechtlichesicherung")
    op.execute("DROP TYPE lp_bioverbundsystemart")
    op.execute("DROP TYPE lp_biovstandortfeuchte")
    op.execute("DROP TYPE lp_umsetzungsstand")
    op.execute("DROP TYPE lp_biovftiereartsystematik")
    op.execute("DROP TYPE lp_biovftierartrechtlicherschutz")
    op.execute("DROP TYPE lp_biovfpflanzenartrechtlicherschutz")
    op.execute("DROP TYPE lp_biovfpflanzenartsystematik")
    op.execute("DROP TYPE lp_biovfbestandteil")
    op.execute("DROP TYPE lp_adressatart")
    op.execute("DROP TYPE lp_erholungfunktionen")
    op.execute("DROP TYPE lp_bodenauspraegung")
    op.execute("DROP TYPE lp_biovftierarthabitatanforderung")
    op.execute("DROP TYPE lp_klassifizierungnaturschutzrecht")
    op.execute("DROP TYPE lp_rechtsstandschutzgeb")
    op.execute("DROP TYPE lp_gesgeschbiotoptyp")
    op.execute("DROP TYPE lp_schutzzonennaturschutzrecht")
    op.execute("DROP TYPE lp_schutzpflegeentwicklung")
    op.execute("DROP TYPE lp_wasserauspraegung")
    op.execute("DROP TYPE lp_zieldimensiontyp")
    op.execute("DROP TYPE lp_zemtyp")
    op.execute("DROP TYPE lp_landschaftsbildart")
    op.execute("DROP TYPE lp_klimaart")
    op.execute("DROP TYPE lp_luftart")
    op.execute("DROP TYPE lp_schutzgutart")

    op.drop_column('codelist_values', 'key')

    op.drop_column('xp_po', 'index')
    op.drop_column('xp_po', 'art')
    op.drop_column('xp_po', 'darstellungsprioritaet')
    # ### end Alembic commands ###
