"""v2.12.0

Revision ID: 315e0f69004f
Revises: 98624e3008ab
Create Date: 2025-11-19 07:50:55.734142

"""
import os
import sys

from alembic import op
import sqlalchemy as sa

from alembic_postgresql_enum import ColumnType
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

PROJECT_PATH = os.getcwd()
SOURCE_PATH = os.path.join(
    PROJECT_PATH, "src"
)
sys.path.append(SOURCE_PATH)


# revision identifiers, used by Alembic.
revision = '315e0f69004f'
down_revision = '98624e3008ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xp_textabschnitt_assoc',
        sa.Column('xp_objekt_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('xp_plan_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('xp_bereich_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('textabschnitt_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['textabschnitt_id'], ['xp_text_abschnitt.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['xp_objekt_id'], ['xp_objekt.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['xp_plan_id'], ['xp_plan.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['xp_bereich_id'], ['xp_bereich.id'], ondelete='CASCADE'),
    )
    # 2. Copy existing FK links into the new association table
    op.execute("""
        INSERT INTO xp_textabschnitt_assoc (xp_objekt_id, xp_plan_id, xp_bereich_id, textabschnitt_id)
        SELECT xp_objekt_id, xp_plan_id, xp_bereich_id, id
        FROM xp_text_abschnitt
        WHERE xp_objekt_id IS NOT NULL OR xp_plan_id IS NOT NULL OR xp_bereich_id IS NOT NULL;
    """)
    op.drop_column("xp_text_abschnitt", "xp_objekt_id")
    op.drop_column("xp_text_abschnitt", "xp_plan_id")
    op.drop_column("xp_text_abschnitt", "xp_bereich_id")

    op.create_table('xp_rasterdarstellung',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('bereich_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['bereich_id'], ['xp_bereich.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('xp_externe_referenz', sa.Column('xp_rasterdarstellung_scan_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('xp_externe_referenz', sa.Column('xp_rasterdarstellung_text_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('xp_externe_referenz', sa.Column('xp_rasterdarstellung_legende_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'xp_externe_referenz', 'xp_rasterdarstellung', ['xp_rasterdarstellung_legende_id'],
                          ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'xp_externe_referenz', 'xp_rasterdarstellung', ['xp_rasterdarstellung_text_id'], ['id'],
                          ondelete='CASCADE')
    op.create_foreign_key(None, 'xp_externe_referenz', 'xp_rasterdarstellung', ['xp_rasterdarstellung_scan_id'], ['id'],
                          ondelete='CASCADE')

    op.add_column('xp_externe_referenz', sa.Column('georef_file', postgresql.BYTEA(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("xp_text_abschnitt",
        sa.Column("xp_objekt_id", postgresql.UUID(as_uuid=True), sa.ForeignKey('xp_objekt.id', ondelete="CASCADE"))
    )
    op.add_column("xp_text_abschnitt",
        sa.Column("xp_plan_id", postgresql.UUID(as_uuid=True), sa.ForeignKey('xp_plan.id', ondelete="CASCADE"))
    )
    op.add_column("xp_text_abschnitt",
        sa.Column("xp_bereich_id", postgresql.UUID(as_uuid=True), sa.ForeignKey('xp_bereich.id', ondelete="CASCADE"))
    )
    op.execute("""
               UPDATE xp_text_abschnitt t
               SET xp_objekt_id = a.xp_objekt_id FROM xp_textabschnitt_assoc a
               WHERE a.textabschnitt_id = t.id
               """)
    op.execute("""
               UPDATE xp_text_abschnitt t
               SET xp_plan_id = a.xp_plan_id FROM xp_textabschnitt_assoc a
               WHERE a.textabschnitt_id = t.id
               """)
    op.execute("""
               UPDATE xp_text_abschnitt t
               SET xp_bereich_id = a.xp_bereich_id FROM xp_textabschnitt_assoc a
               WHERE a.textabschnitt_id = t.id
               """)
    op.drop_table("xp_textabschnitt_assoc")

    op.drop_column('xp_externe_referenz', 'xp_rasterdarstellung_legende_id')
    op.drop_column('xp_externe_referenz', 'xp_rasterdarstellung_text_id')
    op.drop_column('xp_externe_referenz', 'xp_rasterdarstellung_scan_id')
    op.drop_table('xp_rasterdarstellung')

    op.drop_column('xp_externe_referenz', 'georef_file')
    # ### end Alembic commands ###
