"""v2.12.0

Revision ID: 315e0f69004f
Revises: 98624e3008ab
Create Date: 2025-11-19 07:50:55.734142

"""
import os
import sys

from alembic import op
import sqlalchemy as sa

from alembic_postgresql_enum import ColumnType
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

PROJECT_PATH = os.getcwd()
SOURCE_PATH = os.path.join(
    PROJECT_PATH, "src"
)
sys.path.append(SOURCE_PATH)


# revision identifiers, used by Alembic.
revision = '315e0f69004f'
down_revision = '98624e3008ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xp_textabschnitt_assoc',
        sa.Column('xp_objekt_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('textabschnitt_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['textabschnitt_id'], ['xp_text_abschnitt.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['xp_objekt_id'], ['xp_objekt.id'], ondelete='CASCADE'),
    )
    # 2. Copy existing FK links into the new association table
    op.execute("""
        INSERT INTO xp_textabschnitt_assoc (xp_objekt_id, textabschnitt_id)
        SELECT xp_objekt_id, id
        FROM xp_text_abschnitt
        WHERE xp_objekt_id IS NOT NULL
    """)
    op.drop_column("xp_text_abschnitt", "xp_objekt_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("xp_text_abschnitt",
        sa.Column("xp_objekt_id", postgresql.UUID(as_uuid=True), sa.ForeignKey('xp_objekt.id', ondelete="CASCADE"))
    )
    op.execute("""
               UPDATE xp_text_abschnitt t
               SET xp_objekt_id = a.xp_objekt_id FROM xp_textabschnitt_assoc a
               WHERE a.textabschnitt_id = t.id
               """)
    op.drop_table("xp_textabschnitt_assoc")
    # ### end Alembic commands ###
