"""v2.11.0

Revision ID: 98624e3008ab
Revises: da3841c7f8d9
Create Date: 2025-11-07 10:45:30.863759

"""
import os
import sys

from alembic import op
import sqlalchemy as sa

from alembic_postgresql_enum import ColumnType
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

PROJECT_PATH = os.getcwd()
SOURCE_PATH = os.path.join(
    PROJECT_PATH, "src"
)
sys.path.append(SOURCE_PATH)


# revision identifiers, used by Alembic.
revision = '98624e3008ab'
down_revision = 'da3841c7f8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE bp_plan ALTER "planArt" type bp_planart[] using ARRAY["planArt"]')

    op.execute('ALTER TABLE bp_baugebiet ALTER COLUMN "FR" TYPE FLOAT USING "FR"::float;')
    op.execute('ALTER TABLE bp_gemeinbedarf ALTER COLUMN "FR" TYPE FLOAT USING "FR"::float;')
    op.execute('ALTER TABLE bp_wohngebaeude_flaeche ALTER COLUMN "FR" TYPE FLOAT USING "FR"::float;')
    op.execute('ALTER TABLE bp_besondere_nutzung ALTER COLUMN "FR" TYPE FLOAT USING "FR"::float;')
    op.execute('ALTER TABLE bp_grundstueck_ueberbaubar ALTER COLUMN "FR" TYPE FLOAT USING "FR"::float;')

    op.execute('ALTER TABLE bp_dachgestaltung ALTER COLUMN "DNmin" TYPE FLOAT USING "DNmin"::float;')
    op.execute('ALTER TABLE bp_dachgestaltung ALTER COLUMN "DNmax" TYPE FLOAT USING "DNmax"::float;')
    op.execute('ALTER TABLE bp_dachgestaltung ALTER COLUMN "DN" TYPE FLOAT USING "DN"::float;')
    op.execute('ALTER TABLE bp_dachgestaltung ALTER COLUMN "DNZwingend" TYPE FLOAT USING "DNZwingend"::float;')

    op.execute('ALTER TABLE lp_objekt ALTER COLUMN nordwinkel TYPE FLOAT USING nordwinkel::float;')

    op.execute('ALTER TABLE bp_plan ADD CONSTRAINT ck_planart_not_empty_no_nulls CHECK ("planArt" <> \'{}\' and array_position("planArt", null) is null);')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE bp_plan ALTER "planArt" type bp_planart using "planArt"[1]')

    op.execute('ALTER TABLE bp_baugebiet ALTER COLUMN "FR" TYPE integer USING "FR"::integer;')
    op.execute('ALTER TABLE bp_gemeinbedarf ALTER COLUMN "FR" TYPE integer USING "FR"::integer;')
    op.execute('ALTER TABLE bp_wohngebaeude_flaeche ALTER COLUMN "FR" TYPE integer USING "FR"::integer;')
    op.execute('ALTER TABLE bp_besondere_nutzung ALTER COLUMN "FR" TYPE integer USING "FR"::integer;')
    op.execute('ALTER TABLE bp_grundstueck_ueberbaubar ALTER COLUMN "FR" TYPE integer USING "FR"::integer;')

    op.execute('ALTER TABLE bp_dachgestaltung ALTER COLUMN "DNmin" TYPE integer USING "DNmin"::integer;')
    op.execute('ALTER TABLE bp_dachgestaltung ALTER COLUMN "DNmax" TYPE integer USING "DNmax"::integer;')
    op.execute('ALTER TABLE bp_dachgestaltung ALTER COLUMN "DN" TYPE integer USING "DN"::integer;')
    op.execute('ALTER TABLE bp_dachgestaltung ALTER COLUMN "DNZwingend" TYPE integer USING "DNZwingend"::integer;')

    op.execute('ALTER TABLE lp_objekt ALTER COLUMN nordwinkel TYPE integer USING nordwinkel::integer;')

    op.drop_constraint('ck_planart_not_empty_no_nulls', 'bp_plan')
    # ### end Alembic commands ###
