"""v2.8.0

Revision ID: e9b38a472653
Revises: 5b93f2301608
Create Date: 2024-12-10 10:02:36.655202

"""
import os
import sys

from alembic import op
import sqlalchemy as sa

from alembic_postgresql_enum import ColumnType
from alembic_postgresql_enum import TableReference
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

PROJECT_PATH = os.getcwd()
SOURCE_PATH = os.path.join(
    PROJECT_PATH, "src"
)
sys.path.append(SOURCE_PATH)

# revision identifiers, used by Alembic.
revision = 'e9b38a472653'
down_revision = '5b93f2301608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assoc_detail_zweckgemeinbedarf',
                    sa.Column('codelist_user_id', postgresql.UUID(), nullable=True),
                    sa.Column('codelist_user_v6_id', postgresql.UUID(), nullable=True),
                    sa.Column('codelist_id', postgresql.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['codelist_id'], ['codelist_values.id'], ),
                    sa.ForeignKeyConstraint(['codelist_user_id'], ['fp_gemeinbedarf.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['codelist_user_v6_id'], ['fp_zweckbestimmung_gemeinbedarf.id'],
                                            ondelete='CASCADE')
                    )

    op.drop_table('civil_line', if_exists=True)
    op.drop_table('civil_point', if_exists=True)
    op.drop_table('civil_area', if_exists=True)
    op.drop_table('civil_plan', if_exists=True)
    op.drop_table('civil_gemeinde', if_exists=True)

    op.alter_column('bp_komplexe_sondernutzung', 'allgemein',
                    existing_type=postgresql.ENUM('KeineSondernutzung', 'Wochendhausgebiet', 'Ferienhausgebiet',
                                                  'Campingplatzgebiet', 'Kurgebiet', 'SonstSondergebietErholung',
                                                  'Einzelhandelsgebiet', 'GrossflaechigerEinzelhandel', 'Ladengebiet',
                                                  'Einkaufszentrum', 'SonstGrossflEinzelhandel', 'Verkehrsuebungsplatz',
                                                  'Hafengebiet', 'SondergebietErneuerbareEnergie',
                                                  'SondergebietMilitaer', 'SondergebietLandwirtschaft',
                                                  'SondergebietSport', 'SondergebietGesundheitSoziales', 'Klinikgebiet',
                                                  'Golfplatz', 'SondergebietKultur', 'SondergebietTourismus',
                                                  'SondergebietBueroUndVerwaltung', 'SondergebietJustiz',
                                                  'SondergebietHochschuleForschung', 'SondergebietMesse',
                                                  'SondergebietAndereNutzungen', 'SondergebietGrosshandel',
                                                  name='xp_sondernutzungen'),
                    nullable=False)
    op.drop_column('bp_komplexe_sondernutzung', 'detail_id')
    op.alter_column('bp_veraenderungssperre_daten', 'verlaengerung',
                    existing_type=postgresql.ENUM('Keine', 'ErsteVerlaengerung', 'ZweiteVerlaengerung',
                                                  name='bp_verlaengerungveraenderungssperre'),
                    nullable=False)
    op.alter_column('bp_zweckbestimmung_gemeinbedarf', 'allgemein',
                    existing_type=postgresql.ENUM('OeffentlicheVerwaltung', 'KommunaleEinrichtung',
                                                  'BetriebOeffentlZweckbestimmung', 'AnlageBundLand',
                                                  'BildungForschung', 'Schule', 'Hochschule', 'BerufsbildendeSchule',
                                                  'Forschungseinrichtung', 'Kirche', 'Sakralgebaeude',
                                                  'KirchlicheVerwaltung', 'Kirchengemeinde', 'Sozial',
                                                  'EinrichtungKinder', 'EinrichtungJugendliche',
                                                  'EinrichtungFamilienErwachsene', 'EinrichtungSenioren',
                                                  'SonstigeSozialeEinrichtung', 'EinrichtungBehinderte', 'Gesundheit',
                                                  'Krankenhaus', 'Kultur', 'MusikTheater', 'Bildung', 'Sport', 'Bad',
                                                  'SportplatzSporthalle', 'SicherheitOrdnung', 'Feuerwehr',
                                                  'Schutzbauwerk', 'Justiz', 'Infrastruktur', 'Post', 'Sonstiges',
                                                  'SonstigeInfrastruktur', 'SonstigeSicherheitOrdnung',
                                                  name='xp_zweckbestimmunggemeinbedarf'),
                    nullable=False)
    op.alter_column('bp_zweckbestimmung_gruen', 'allgemein',
                    existing_type=postgresql.ENUM('Parkanlage', 'ParkanlageHistorisch', 'ParkanlageNaturnah',
                                                  'ParkanlageWaldcharakter', 'NaturnaheUferParkanlage',
                                                  'Dauerkleingarten', 'ErholungsGaerten', 'Sportplatz',
                                                  'Reitsportanlage', 'Hundesportanlage', 'Wassersportanlage',
                                                  'Schiessstand', 'Golfplatz', 'Skisport', 'Tennisanlage', 'Spielplatz',
                                                  'Bolzplatz', 'Abenteuerspielplatz', 'Zeltplatz', 'Campingplatz',
                                                  'Badeplatz', 'FreizeitErholung', 'Kleintierhaltung', 'Festplatz',
                                                  'SpezGruenflaeche', 'StrassenbegleitGruen', 'BoeschungsFlaeche',
                                                  'FeldWaldWiese', 'Uferschutzstreifen', 'Abschirmgruen',
                                                  'UmweltbildungsparkSchaugatter', 'RuhenderVerkehr', 'Friedhof',
                                                  'Sonstiges', 'Gaertnerei', 'Naturerfahrungsraum',
                                                  name='xp_zweckbestimmunggruen'),
                    nullable=False)
    op.drop_column('bp_zweckbestimmung_gruen', 'detail_id')
    op.alter_column('bp_zweckbestimmung_landwirtschaft', 'allgemein',
                    existing_type=postgresql.ENUM('LandwirtschaftAllgemein', 'Ackerbau', 'WiesenWeidewirtschaft',
                                                  'GartenbaulicheErzeugung', 'Obstbau', 'Weinbau', 'Imkerei',
                                                  'Binnenfischerei', 'Sonstiges',
                                                  name='xp_zweckbestimmunglandwirtschaft'),
                    nullable=False)
    op.alter_column('bp_zweckbestimmung_nebenanlagen', 'allgemein',
                    existing_type=postgresql.ENUM('Stellplaetze', 'Garagen', 'Spielplatz', 'Carport', 'Tiefgarage',
                                                  'Nebengebaeude', 'AbfallSammelanlagen', 'EnergieVerteilungsanlagen',
                                                  'AbfallWertstoffbehaelter', 'Fahrradstellplaetze', 'Sonstiges',
                                                  name='bp_zweckbestimmungnebenanlagen'),
                    nullable=False)
    op.alter_column('bp_zweckbestimmung_sport', 'allgemein',
                    existing_type=postgresql.ENUM('Sportanlage', 'Spielanlage', 'SpielSportanlage', 'Sonstiges',
                                                  name='xp_zweckbestimmungspielsportanlage'),
                    nullable=False)
    op.alter_column('bp_zweckbestimmung_versorgung', 'allgemein',
                    existing_type=postgresql.ENUM('Elektrizitaet', 'Hochspannungsleitung', 'TrafostationUmspannwerk',
                                                  'Solarkraftwerk', 'Windkraftwerk', 'Geothermiekraftwerk',
                                                  'Elektrizitaetswerk', 'Wasserkraftwerk', 'BiomasseKraftwerk',
                                                  'Kabelleitung', 'Niederspannungsleitung', 'Leitungsmast',
                                                  'Kernkraftwerk', 'Kohlekraftwerk', 'Gaskraftwerk', 'Gas',
                                                  'Ferngasleitung', 'Gaswerk', 'Gasbehaelter', 'Gasdruckregler',
                                                  'Gasstation', 'Gasleitung', 'Erdoel', 'Erdoelleitung', 'Bohrstelle',
                                                  'Erdoelpumpstation', 'Oeltank', 'Waermeversorgung',
                                                  'Blockheizkraftwerk', 'Fernwaermeleitung', 'Fernheizwerk', 'Wasser',
                                                  'Wasserwerk', 'Wasserleitung', 'Wasserspeicher', 'Brunnen',
                                                  'Pumpwerk', 'Quelle', 'Abwasser', 'Abwasserleitung',
                                                  'Abwasserrueckhaltebecken', 'Abwasserpumpwerk', 'Klaeranlage',
                                                  'AnlageKlaerschlamm', 'SonstigeAbwasserBehandlungsanlage',
                                                  'SalzOderSoleleitungen', 'Regenwasser', 'RegenwasserRueckhaltebecken',
                                                  'Niederschlagswasserleitung', 'Abfallentsorgung',
                                                  'Muellumladestation', 'Muellbeseitigungsanlage', 'Muellsortieranlage',
                                                  'Recyclinghof', 'Ablagerung', 'Erdaushubdeponie', 'Bauschuttdeponie',
                                                  'Hausmuelldeponie', 'Sondermuelldeponie', 'StillgelegteDeponie',
                                                  'RekultivierteDeponie', 'Telekommunikation', 'Fernmeldeanlage',
                                                  'Mobilfunkanlage', 'Fernmeldekabel', 'ErneuerbareEnergien',
                                                  'KraftWaermeKopplung', 'Sonstiges', 'Produktenleitung',
                                                  name='xp_zweckbestimmungverentsorgung'),
                    nullable=False)
    op.alter_column('bp_zweckbestimmung_wald', 'allgemein',
                    existing_type=postgresql.ENUM('Naturwald', 'Waldschutzgebiet', 'Nutzwald', 'Erholungswald',
                                                  'Schutzwald', 'Bodenschutzwald', 'Biotopschutzwald', 'NaturnaherWald',
                                                  'SchutzwaldSchaedlicheUmwelteinwirkungen', 'Schonwald', 'Bannwald',
                                                  'FlaecheForstwirtschaft', 'ImmissionsgeschaedigterWald', 'Sonstiges',
                                                  name='xp_zweckbestimmungwald'),
                    nullable=False)
    op.alter_column('fp_komplexe_sondernutzung', 'allgemein',
                    existing_type=postgresql.ENUM('KeineSondernutzung', 'Wochendhausgebiet', 'Ferienhausgebiet',
                                                  'Campingplatzgebiet', 'Kurgebiet', 'SonstSondergebietErholung',
                                                  'Einzelhandelsgebiet', 'GrossflaechigerEinzelhandel', 'Ladengebiet',
                                                  'Einkaufszentrum', 'SonstGrossflEinzelhandel', 'Verkehrsuebungsplatz',
                                                  'Hafengebiet', 'SondergebietErneuerbareEnergie',
                                                  'SondergebietMilitaer', 'SondergebietLandwirtschaft',
                                                  'SondergebietSport', 'SondergebietGesundheitSoziales', 'Klinikgebiet',
                                                  'Golfplatz', 'SondergebietKultur', 'SondergebietTourismus',
                                                  'SondergebietBueroUndVerwaltung', 'SondergebietJustiz',
                                                  'SondergebietHochschuleForschung', 'SondergebietMesse',
                                                  'SondergebietAndereNutzungen', 'SondergebietGrosshandel',
                                                  name='xp_sondernutzungen'),
                    nullable=False)
    op.alter_column('fp_zweckbestimmung_gemeinbedarf', 'allgemein',
                    existing_type=postgresql.ENUM('OeffentlicheVerwaltung', 'KommunaleEinrichtung',
                                                  'BetriebOeffentlZweckbestimmung', 'AnlageBundLand',
                                                  'BildungForschung', 'Schule', 'Hochschule', 'BerufsbildendeSchule',
                                                  'Forschungseinrichtung', 'Kirche', 'Sakralgebaeude',
                                                  'KirchlicheVerwaltung', 'Kirchengemeinde', 'Sozial',
                                                  'EinrichtungKinder', 'EinrichtungJugendliche',
                                                  'EinrichtungFamilienErwachsene', 'EinrichtungSenioren',
                                                  'SonstigeSozialeEinrichtung', 'EinrichtungBehinderte', 'Gesundheit',
                                                  'Krankenhaus', 'Kultur', 'MusikTheater', 'Bildung', 'Sport', 'Bad',
                                                  'SportplatzSporthalle', 'SicherheitOrdnung', 'Feuerwehr',
                                                  'Schutzbauwerk', 'Justiz', 'Infrastruktur', 'Post', 'Sonstiges',
                                                  'SonstigeInfrastruktur', 'SonstigeSicherheitOrdnung',
                                                  name='xp_zweckbestimmunggemeinbedarf'),
                    nullable=False)
    op.alter_column('fp_zweckbestimmung_gruen', 'allgemein',
                    existing_type=postgresql.ENUM('Parkanlage', 'ParkanlageHistorisch', 'ParkanlageNaturnah',
                                                  'ParkanlageWaldcharakter', 'NaturnaheUferParkanlage',
                                                  'Dauerkleingarten', 'ErholungsGaerten', 'Sportplatz',
                                                  'Reitsportanlage', 'Hundesportanlage', 'Wassersportanlage',
                                                  'Schiessstand', 'Golfplatz', 'Skisport', 'Tennisanlage', 'Spielplatz',
                                                  'Bolzplatz', 'Abenteuerspielplatz', 'Zeltplatz', 'Campingplatz',
                                                  'Badeplatz', 'FreizeitErholung', 'Kleintierhaltung', 'Festplatz',
                                                  'SpezGruenflaeche', 'StrassenbegleitGruen', 'BoeschungsFlaeche',
                                                  'FeldWaldWiese', 'Uferschutzstreifen', 'Abschirmgruen',
                                                  'UmweltbildungsparkSchaugatter', 'RuhenderVerkehr', 'Friedhof',
                                                  'Sonstiges', 'Gaertnerei', 'Naturerfahrungsraum',
                                                  name='xp_zweckbestimmunggruen'),
                    nullable=False)
    op.alter_column('fp_zweckbestimmung_landwirtschaft', 'allgemein',
                    existing_type=postgresql.ENUM('LandwirtschaftAllgemein', 'Ackerbau', 'WiesenWeidewirtschaft',
                                                  'GartenbaulicheErzeugung', 'Obstbau', 'Weinbau', 'Imkerei',
                                                  'Binnenfischerei', 'Sonstiges',
                                                  name='xp_zweckbestimmunglandwirtschaft'),
                    nullable=False)
    op.alter_column('fp_zweckbestimmung_sport', 'allgemein',
                    existing_type=postgresql.ENUM('Sportanlage', 'Spielanlage', 'SpielSportanlage', 'Sonstiges',
                                                  name='xp_zweckbestimmungspielsportanlage'),
                    nullable=False)
    op.drop_column('fp_zweckbestimmung_versorgung', 'detail_id')
    op.alter_column('fp_zweckbestimmung_wald', 'allgemein',
                    existing_type=postgresql.ENUM('Naturwald', 'Waldschutzgebiet', 'Nutzwald', 'Erholungswald',
                                                  'Schutzwald', 'Bodenschutzwald', 'Biotopschutzwald', 'NaturnaherWald',
                                                  'SchutzwaldSchaedlicheUmwelteinwirkungen', 'Schonwald', 'Bannwald',
                                                  'FlaecheForstwirtschaft', 'ImmissionsgeschaedigterWald', 'Sonstiges',
                                                  name='xp_zweckbestimmungwald'),
                    nullable=False)
    op.alter_column('so_festlegung_gewaesser', 'allgemein',
                    existing_type=postgresql.ENUM('Gewaesser', 'Fliessgewaesser', 'Gewaesser1Ordnung',
                                                  'Gewaesser2Ordnung', 'Gewaesser3Ordnung', 'StehendesGewaesser',
                                                  'Hafen', 'Sportboothafen', 'Wasserstrasse', 'Kanal', 'Sonstiges',
                                                  name='so_klassifizgewaesser'),
                    nullable=False)
    op.alter_column('so_zweckbestimmung_strassenverkehr', 'allgemein',
                    existing_type=postgresql.ENUM('AutobahnUndAehnlich', 'Hauptverkehrsstrasse',
                                                  'SonstigerVerkehrswegAnlage', 'VerkehrsberuhigterBereich', 'Platz',
                                                  'Fussgaengerbereich', 'RadGehweg', 'Radweg', 'Gehweg', 'Wanderweg',
                                                  'ReitKutschweg', 'Rastanlage', 'Busbahnhof',
                                                  'UeberfuehrenderVerkehrsweg', 'UnterfuehrenderVerkehrsweg',
                                                  'Wirtschaftsweg', 'LandwirtschaftlicherVerkehr', 'Anschlussflaeche',
                                                  'Verkehrsgruen', 'RuhenderVerkehr', 'Parkplatz',
                                                  'FahrradAbstellplatz', 'P_RAnlage', 'B_RAnlage', 'Parkhaus',
                                                  'CarSharing', 'BikeSharing', 'Mischverkehrsflaeche', 'Ladestation',
                                                  'Sonstiges', name='so_zweckbestimmungstrassenverkehr'),
                    nullable=False)

    op.alter_column('xp_objekt', 'rechtscharakter',
                    existing_type=postgresql.ENUM('FestsetzungBPlan', 'NachrichtlicheUebernahme', 'DarstellungFPlan',
                                                  'ZielDerRaumordnung', 'GrundsatzDerRaumordnung',
                                                  'NachrichtlicheUebernahmeZiel', 'NachrichtlicheUebernahmeGrundsatz',
                                                  'NurInformationsgehaltRPlan', 'TextlichesZielRaumordnung',
                                                  'ZielUndGrundsatzRaumordnung', 'VorschlagRaumordnung',
                                                  'FestsetzungImLP', 'GeplanteFestsetzungImLP',
                                                  'DarstellungKennzeichnungImLP',
                                                  'LandschaftsplanungsInhaltZurBeruecksichtigung', 'Hinweis',
                                                  'Kennzeichnung', 'Vermerk', 'Unbekannt', 'Sonstiges',
                                                  name='xp_rechtscharakter'),
                    nullable=False)

    op.alter_column('xp_plan', 'raeumlicherGeltungsbereich',
                    existing_type=Geometry(from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
                    nullable=False)

    # delete rows that violate new geometry check constraint, then insert new constraint
    op.execute("""
        DELETE FROM xp_objekt 
        WHERE id IN (
            SELECT id FROM bp_objekt WHERE GeometryType(position) IN ('GEOMETRYCOLLECTION')
        );

        DELETE FROM bp_objekt WHERE GeometryType(position) IN ('GEOMETRYCOLLECTION');

        DELETE FROM xp_objekt 
        WHERE id IN (
            SELECT id FROM fp_objekt WHERE GeometryType(position) IN ('GEOMETRYCOLLECTION')
        );

        DELETE FROM fp_objekt WHERE GeometryType(position) IN ('GEOMETRYCOLLECTION');

        DELETE FROM xp_objekt 
        WHERE id IN (
            SELECT id FROM so_objekt WHERE GeometryType(position) IN ('GEOMETRYCOLLECTION')
        );

        DELETE FROM so_objekt WHERE GeometryType(position) IN ('GEOMETRYCOLLECTION');
    """)
    op.create_check_constraint("prevent_geometry_collection", "bp_objekt",
                               "GeometryType(position) NOT IN ('GEOMETRYCOLLECTION')")
    op.create_check_constraint("prevent_geometry_collection", "fp_objekt",
                               "GeometryType(position) NOT IN ('GEOMETRYCOLLECTION')")
    op.create_check_constraint("prevent_geometry_collection", "so_objekt",
                               "GeometryType(position) NOT IN ('GEOMETRYCOLLECTION')")

    # merge so_strassenverkehr / so_strassenverkehrsrecht
    op.create_table('so_strassenverkehrsrecht',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('artDerFestlegung', sa.Enum('Bundesautobahn', 'Bundesstrasse', 'LandesStaatsstrasse',
                                              'Kreisstrasse', 'SonstOeffentlStrasse',
                                              name='so_klassifiznachstrassenverkehrsrecht'), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('nummer', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['so_objekt.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.execute("""
        CREATE OR REPLACE FUNCTION temp_convert(v_input text)
        RETURNS so_klassifiznachstrassenverkehrsrecht AS $$
        DECLARE ret so_klassifiznachstrassenverkehrsrecht DEFAULT NULL;
        BEGIN
            BEGIN
                ret := v_input::so_klassifiznachstrassenverkehrsrecht;
            EXCEPTION WHEN OTHERS THEN
                RAISE NOTICE 'Invalid so_klassifiznachstrassenverkehrsrecht value: "%".  Returning Default.', v_input;
                RETURN 'SonstOeffentlStrasse'::so_klassifiznachstrassenverkehrsrecht;
            END;
        RETURN ret;
        END;
        $$ LANGUAGE plpgsql;

        WITH old_and_new_ids AS (
            SELECT 
                uuid_generate_v4() AS new_id, -- new id to be inserted
                'so_strassenverkehrsrecht' AS type,
                xp.rechtscharakter,
                str.id AS old_id -- capturing old id, needed later for merging data
            FROM so_strassenverkehr str
            JOIN xp_objekt xp ON xp.id = str.id
        ),
        -- Step 2: insert into xo_objekt
        new_xp_objekt AS (
            INSERT INTO xp_objekt (id, type, rechtscharakter, uuid, text, rechtsstand, gliederung1, gliederung2, ebene, "gehoertZuBereich_id", aufschrift, "gesetzlicheGrundlage_id", skalierung, drehwinkel)
            SELECT 
                new_id,
                oani.type,
                oani.rechtscharakter,
                uuid, text, rechtsstand, gliederung1, gliederung2, ebene, "gehoertZuBereich_id", aufschrift, "gesetzlicheGrundlage_id", skalierung, drehwinkel
            FROM old_and_new_ids oani
            JOIN xp_objekt xp ON oani.old_id=xp.id
            RETURNING id, type, rechtscharakter
        ),
        -- Step 2: insert into so_objekt
        new_so_objekt AS (
            INSERT INTO so_objekt (id, rechtscharakter, position, flaechenschluss, flussrichtung, nordwinkel)
            SELECT 
                new.id as id, 
                so.rechtscharakter as rechtscharakter,
                position, flaechenschluss, flussrichtung, nordwinkel
            FROM new_xp_objekt new
            JOIN old_and_new_ids oani ON new.id = oani.new_id
            JOIN so_objekt so ON oani.old_id=so.id
            RETURNING id, rechtscharakter
        )
        
        -- Step 3: insert into so_strassenverkehrsrecht
        INSERT INTO so_strassenverkehrsrecht (id, name, nummer, "artDerFestlegung")
          SELECT
            oani.new_id AS id, 
            s.name, s.nummer, 
            temp_convert(s.einteilung::text) AS "artDerFestlegung"
        FROM so_strassenverkehr s
        JOIN old_and_new_ids oani ON s.id = oani.old_id;
        
        DROP function temp_convert(v_input text);
    """
    )

    # fix gewaesser in v5
    new_enum = postgresql.ENUM('Gewaesser', 'Fliessgewaesser', 'Gewaesser1Ordnung', 'Gewaesser2Ordnung',
                               'Gewaesser3Ordnung', 'StehendesGewaesser', 'Hafen', 'Sonstiges',
                               name='so_klassifizgewaesserv5')
    new_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('so_gewaesser', sa.Column('artDerFestlegung', new_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('fp_zweckbestimmung_versorgung', sa.Column('detail_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('bp_zweckbestimmung_gruen', sa.Column('detail_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('bp_komplexe_sondernutzung', sa.Column('detail_id', postgresql.UUID(), autoincrement=False, nullable=True))

    op.drop_table('assoc_detail_zweckgemeinbedarf')

    op.drop_constraint("prevent_geometry_collection", "bp_objekt", type_="check")
    op.drop_constraint("prevent_geometry_collection", "fp_objekt", type_="check")
    op.drop_constraint("prevent_geometry_collection", "so_objekt", type_="check")

    op.drop_table('so_strassenverkehrsrecht')
    op.execute("DROP TYPE so_klassifiznachstrassenverkehrsrecht")
    op.execute("DELETE FROM xp_objekt CASCADE WHERE type in ('so_strassenverkehrsrecht')")

    op.drop_column('so_gewaesser', 'artDerFestlegung')
    op.execute("DROP TYPE so_klassifizgewaesserv5")
    # ### end Alembic commands ###
