"""v2.8.0

Revision ID: e9b38a472653
Revises: 5b93f2301608
Create Date: 2024-12-10 10:02:36.655202

"""
import os
import sys

from alembic import op
import sqlalchemy as sa

from alembic_postgresql_enum import ColumnType
from alembic_postgresql_enum import TableReference
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

PROJECT_PATH = os.getcwd()
SOURCE_PATH = os.path.join(
    PROJECT_PATH, "src"
)
sys.path.append(SOURCE_PATH)

# revision identifiers, used by Alembic.
revision = 'e9b38a472653'
down_revision = '5b93f2301608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assoc_detail_zweckgemeinbedarf',
                    sa.Column('codelist_user_id', postgresql.UUID(), nullable=True),
                    sa.Column('codelist_user_v6_id', postgresql.UUID(), nullable=True),
                    sa.Column('codelist_id', postgresql.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['codelist_id'], ['codelist_values.id'], ),
                    sa.ForeignKeyConstraint(['codelist_user_id'], ['fp_gemeinbedarf.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['codelist_user_v6_id'], ['fp_zweckbestimmung_gemeinbedarf.id'],
                                            ondelete='CASCADE')
                    )

    op.drop_table('civil_line', if_exists=True)
    op.drop_table('civil_point', if_exists=True)
    op.drop_table('civil_area', if_exists=True)
    op.drop_table('civil_plan', if_exists=True)
    op.drop_table('civil_gemeinde', if_exists=True)

    op.alter_column('bp_komplexe_sondernutzung', 'allgemein',
                    existing_type=postgresql.ENUM('KeineSondernutzung', 'Wochendhausgebiet', 'Ferienhausgebiet',
                                                  'Campingplatzgebiet', 'Kurgebiet', 'SonstSondergebietErholung',
                                                  'Einzelhandelsgebiet', 'GrossflaechigerEinzelhandel', 'Ladengebiet',
                                                  'Einkaufszentrum', 'SonstGrossflEinzelhandel', 'Verkehrsuebungsplatz',
                                                  'Hafengebiet', 'SondergebietErneuerbareEnergie',
                                                  'SondergebietMilitaer', 'SondergebietLandwirtschaft',
                                                  'SondergebietSport', 'SondergebietGesundheitSoziales', 'Klinikgebiet',
                                                  'Golfplatz', 'SondergebietKultur', 'SondergebietTourismus',
                                                  'SondergebietBueroUndVerwaltung', 'SondergebietJustiz',
                                                  'SondergebietHochschuleForschung', 'SondergebietMesse',
                                                  'SondergebietAndereNutzungen', 'SondergebietGrosshandel',
                                                  name='xp_sondernutzungen'),
                    nullable=False)
    op.drop_column('bp_komplexe_sondernutzung', 'detail_id')
    op.alter_column('bp_veraenderungssperre_daten', 'verlaengerung',
                    existing_type=postgresql.ENUM('Keine', 'ErsteVerlaengerung', 'ZweiteVerlaengerung',
                                                  name='bp_verlaengerungveraenderungssperre'),
                    nullable=False)
    op.alter_column('bp_zweckbestimmung_gemeinbedarf', 'allgemein',
                    existing_type=postgresql.ENUM('OeffentlicheVerwaltung', 'KommunaleEinrichtung',
                                                  'BetriebOeffentlZweckbestimmung', 'AnlageBundLand',
                                                  'BildungForschung', 'Schule', 'Hochschule', 'BerufsbildendeSchule',
                                                  'Forschungseinrichtung', 'Kirche', 'Sakralgebaeude',
                                                  'KirchlicheVerwaltung', 'Kirchengemeinde', 'Sozial',
                                                  'EinrichtungKinder', 'EinrichtungJugendliche',
                                                  'EinrichtungFamilienErwachsene', 'EinrichtungSenioren',
                                                  'SonstigeSozialeEinrichtung', 'EinrichtungBehinderte', 'Gesundheit',
                                                  'Krankenhaus', 'Kultur', 'MusikTheater', 'Bildung', 'Sport', 'Bad',
                                                  'SportplatzSporthalle', 'SicherheitOrdnung', 'Feuerwehr',
                                                  'Schutzbauwerk', 'Justiz', 'Infrastruktur', 'Post', 'Sonstiges',
                                                  'SonstigeInfrastruktur', 'SonstigeSicherheitOrdnung',
                                                  name='xp_zweckbestimmunggemeinbedarf'),
                    nullable=False)
    op.alter_column('bp_zweckbestimmung_gruen', 'allgemein',
                    existing_type=postgresql.ENUM('Parkanlage', 'ParkanlageHistorisch', 'ParkanlageNaturnah',
                                                  'ParkanlageWaldcharakter', 'NaturnaheUferParkanlage',
                                                  'Dauerkleingarten', 'ErholungsGaerten', 'Sportplatz',
                                                  'Reitsportanlage', 'Hundesportanlage', 'Wassersportanlage',
                                                  'Schiessstand', 'Golfplatz', 'Skisport', 'Tennisanlage', 'Spielplatz',
                                                  'Bolzplatz', 'Abenteuerspielplatz', 'Zeltplatz', 'Campingplatz',
                                                  'Badeplatz', 'FreizeitErholung', 'Kleintierhaltung', 'Festplatz',
                                                  'SpezGruenflaeche', 'StrassenbegleitGruen', 'BoeschungsFlaeche',
                                                  'FeldWaldWiese', 'Uferschutzstreifen', 'Abschirmgruen',
                                                  'UmweltbildungsparkSchaugatter', 'RuhenderVerkehr', 'Friedhof',
                                                  'Sonstiges', 'Gaertnerei', 'Naturerfahrungsraum',
                                                  name='xp_zweckbestimmunggruen'),
                    nullable=False)
    op.drop_column('bp_zweckbestimmung_gruen', 'detail_id')
    op.alter_column('bp_zweckbestimmung_landwirtschaft', 'allgemein',
                    existing_type=postgresql.ENUM('LandwirtschaftAllgemein', 'Ackerbau', 'WiesenWeidewirtschaft',
                                                  'GartenbaulicheErzeugung', 'Obstbau', 'Weinbau', 'Imkerei',
                                                  'Binnenfischerei', 'Sonstiges',
                                                  name='xp_zweckbestimmunglandwirtschaft'),
                    nullable=False)
    op.alter_column('bp_zweckbestimmung_nebenanlagen', 'allgemein',
                    existing_type=postgresql.ENUM('Stellplaetze', 'Garagen', 'Spielplatz', 'Carport', 'Tiefgarage',
                                                  'Nebengebaeude', 'AbfallSammelanlagen', 'EnergieVerteilungsanlagen',
                                                  'AbfallWertstoffbehaelter', 'Fahrradstellplaetze', 'Sonstiges',
                                                  name='bp_zweckbestimmungnebenanlagen'),
                    nullable=False)
    op.alter_column('bp_zweckbestimmung_sport', 'allgemein',
                    existing_type=postgresql.ENUM('Sportanlage', 'Spielanlage', 'SpielSportanlage', 'Sonstiges',
                                                  name='xp_zweckbestimmungspielsportanlage'),
                    nullable=False)
    op.alter_column('bp_zweckbestimmung_versorgung', 'allgemein',
                    existing_type=postgresql.ENUM('Elektrizitaet', 'Hochspannungsleitung', 'TrafostationUmspannwerk',
                                                  'Solarkraftwerk', 'Windkraftwerk', 'Geothermiekraftwerk',
                                                  'Elektrizitaetswerk', 'Wasserkraftwerk', 'BiomasseKraftwerk',
                                                  'Kabelleitung', 'Niederspannungsleitung', 'Leitungsmast',
                                                  'Kernkraftwerk', 'Kohlekraftwerk', 'Gaskraftwerk', 'Gas',
                                                  'Ferngasleitung', 'Gaswerk', 'Gasbehaelter', 'Gasdruckregler',
                                                  'Gasstation', 'Gasleitung', 'Erdoel', 'Erdoelleitung', 'Bohrstelle',
                                                  'Erdoelpumpstation', 'Oeltank', 'Waermeversorgung',
                                                  'Blockheizkraftwerk', 'Fernwaermeleitung', 'Fernheizwerk', 'Wasser',
                                                  'Wasserwerk', 'Wasserleitung', 'Wasserspeicher', 'Brunnen',
                                                  'Pumpwerk', 'Quelle', 'Abwasser', 'Abwasserleitung',
                                                  'Abwasserrueckhaltebecken', 'Abwasserpumpwerk', 'Klaeranlage',
                                                  'AnlageKlaerschlamm', 'SonstigeAbwasserBehandlungsanlage',
                                                  'SalzOderSoleleitungen', 'Regenwasser', 'RegenwasserRueckhaltebecken',
                                                  'Niederschlagswasserleitung', 'Abfallentsorgung',
                                                  'Muellumladestation', 'Muellbeseitigungsanlage', 'Muellsortieranlage',
                                                  'Recyclinghof', 'Ablagerung', 'Erdaushubdeponie', 'Bauschuttdeponie',
                                                  'Hausmuelldeponie', 'Sondermuelldeponie', 'StillgelegteDeponie',
                                                  'RekultivierteDeponie', 'Telekommunikation', 'Fernmeldeanlage',
                                                  'Mobilfunkanlage', 'Fernmeldekabel', 'ErneuerbareEnergien',
                                                  'KraftWaermeKopplung', 'Sonstiges', 'Produktenleitung',
                                                  name='xp_zweckbestimmungverentsorgung'),
                    nullable=False)
    op.alter_column('bp_zweckbestimmung_wald', 'allgemein',
                    existing_type=postgresql.ENUM('Naturwald', 'Waldschutzgebiet', 'Nutzwald', 'Erholungswald',
                                                  'Schutzwald', 'Bodenschutzwald', 'Biotopschutzwald', 'NaturnaherWald',
                                                  'SchutzwaldSchaedlicheUmwelteinwirkungen', 'Schonwald', 'Bannwald',
                                                  'FlaecheForstwirtschaft', 'ImmissionsgeschaedigterWald', 'Sonstiges',
                                                  name='xp_zweckbestimmungwald'),
                    nullable=False)
    op.alter_column('fp_komplexe_sondernutzung', 'allgemein',
                    existing_type=postgresql.ENUM('KeineSondernutzung', 'Wochendhausgebiet', 'Ferienhausgebiet',
                                                  'Campingplatzgebiet', 'Kurgebiet', 'SonstSondergebietErholung',
                                                  'Einzelhandelsgebiet', 'GrossflaechigerEinzelhandel', 'Ladengebiet',
                                                  'Einkaufszentrum', 'SonstGrossflEinzelhandel', 'Verkehrsuebungsplatz',
                                                  'Hafengebiet', 'SondergebietErneuerbareEnergie',
                                                  'SondergebietMilitaer', 'SondergebietLandwirtschaft',
                                                  'SondergebietSport', 'SondergebietGesundheitSoziales', 'Klinikgebiet',
                                                  'Golfplatz', 'SondergebietKultur', 'SondergebietTourismus',
                                                  'SondergebietBueroUndVerwaltung', 'SondergebietJustiz',
                                                  'SondergebietHochschuleForschung', 'SondergebietMesse',
                                                  'SondergebietAndereNutzungen', 'SondergebietGrosshandel',
                                                  name='xp_sondernutzungen'),
                    nullable=False)
    op.alter_column('fp_zweckbestimmung_gemeinbedarf', 'allgemein',
                    existing_type=postgresql.ENUM('OeffentlicheVerwaltung', 'KommunaleEinrichtung',
                                                  'BetriebOeffentlZweckbestimmung', 'AnlageBundLand',
                                                  'BildungForschung', 'Schule', 'Hochschule', 'BerufsbildendeSchule',
                                                  'Forschungseinrichtung', 'Kirche', 'Sakralgebaeude',
                                                  'KirchlicheVerwaltung', 'Kirchengemeinde', 'Sozial',
                                                  'EinrichtungKinder', 'EinrichtungJugendliche',
                                                  'EinrichtungFamilienErwachsene', 'EinrichtungSenioren',
                                                  'SonstigeSozialeEinrichtung', 'EinrichtungBehinderte', 'Gesundheit',
                                                  'Krankenhaus', 'Kultur', 'MusikTheater', 'Bildung', 'Sport', 'Bad',
                                                  'SportplatzSporthalle', 'SicherheitOrdnung', 'Feuerwehr',
                                                  'Schutzbauwerk', 'Justiz', 'Infrastruktur', 'Post', 'Sonstiges',
                                                  'SonstigeInfrastruktur', 'SonstigeSicherheitOrdnung',
                                                  name='xp_zweckbestimmunggemeinbedarf'),
                    nullable=False)
    op.alter_column('fp_zweckbestimmung_gruen', 'allgemein',
                    existing_type=postgresql.ENUM('Parkanlage', 'ParkanlageHistorisch', 'ParkanlageNaturnah',
                                                  'ParkanlageWaldcharakter', 'NaturnaheUferParkanlage',
                                                  'Dauerkleingarten', 'ErholungsGaerten', 'Sportplatz',
                                                  'Reitsportanlage', 'Hundesportanlage', 'Wassersportanlage',
                                                  'Schiessstand', 'Golfplatz', 'Skisport', 'Tennisanlage', 'Spielplatz',
                                                  'Bolzplatz', 'Abenteuerspielplatz', 'Zeltplatz', 'Campingplatz',
                                                  'Badeplatz', 'FreizeitErholung', 'Kleintierhaltung', 'Festplatz',
                                                  'SpezGruenflaeche', 'StrassenbegleitGruen', 'BoeschungsFlaeche',
                                                  'FeldWaldWiese', 'Uferschutzstreifen', 'Abschirmgruen',
                                                  'UmweltbildungsparkSchaugatter', 'RuhenderVerkehr', 'Friedhof',
                                                  'Sonstiges', 'Gaertnerei', 'Naturerfahrungsraum',
                                                  name='xp_zweckbestimmunggruen'),
                    nullable=False)
    op.alter_column('fp_zweckbestimmung_landwirtschaft', 'allgemein',
                    existing_type=postgresql.ENUM('LandwirtschaftAllgemein', 'Ackerbau', 'WiesenWeidewirtschaft',
                                                  'GartenbaulicheErzeugung', 'Obstbau', 'Weinbau', 'Imkerei',
                                                  'Binnenfischerei', 'Sonstiges',
                                                  name='xp_zweckbestimmunglandwirtschaft'),
                    nullable=False)
    op.alter_column('fp_zweckbestimmung_sport', 'allgemein',
                    existing_type=postgresql.ENUM('Sportanlage', 'Spielanlage', 'SpielSportanlage', 'Sonstiges',
                                                  name='xp_zweckbestimmungspielsportanlage'),
                    nullable=False)
    op.drop_column('fp_zweckbestimmung_versorgung', 'detail_id')
    op.alter_column('fp_zweckbestimmung_wald', 'allgemein',
                    existing_type=postgresql.ENUM('Naturwald', 'Waldschutzgebiet', 'Nutzwald', 'Erholungswald',
                                                  'Schutzwald', 'Bodenschutzwald', 'Biotopschutzwald', 'NaturnaherWald',
                                                  'SchutzwaldSchaedlicheUmwelteinwirkungen', 'Schonwald', 'Bannwald',
                                                  'FlaecheForstwirtschaft', 'ImmissionsgeschaedigterWald', 'Sonstiges',
                                                  name='xp_zweckbestimmungwald'),
                    nullable=False)
    op.alter_column('so_festlegung_gewaesser', 'allgemein',
                    existing_type=postgresql.ENUM('Gewaesser', 'Fliessgewaesser', 'Gewaesser1Ordnung',
                                                  'Gewaesser2Ordnung', 'Gewaesser3Ordnung', 'StehendesGewaesser',
                                                  'Hafen', 'Sportboothafen', 'Wasserstrasse', 'Kanal', 'Sonstiges',
                                                  name='so_klassifizgewaesser'),
                    nullable=False)
    op.alter_column('so_zweckbestimmung_strassenverkehr', 'allgemein',
                    existing_type=postgresql.ENUM('AutobahnUndAehnlich', 'Hauptverkehrsstrasse',
                                                  'SonstigerVerkehrswegAnlage', 'VerkehrsberuhigterBereich', 'Platz',
                                                  'Fussgaengerbereich', 'RadGehweg', 'Radweg', 'Gehweg', 'Wanderweg',
                                                  'ReitKutschweg', 'Rastanlage', 'Busbahnhof',
                                                  'UeberfuehrenderVerkehrsweg', 'UnterfuehrenderVerkehrsweg',
                                                  'Wirtschaftsweg', 'LandwirtschaftlicherVerkehr', 'Anschlussflaeche',
                                                  'Verkehrsgruen', 'RuhenderVerkehr', 'Parkplatz',
                                                  'FahrradAbstellplatz', 'P_RAnlage', 'B_RAnlage', 'Parkhaus',
                                                  'CarSharing', 'BikeSharing', 'Mischverkehrsflaeche', 'Ladestation',
                                                  'Sonstiges', name='so_zweckbestimmungstrassenverkehr'),
                    nullable=False)

    op.alter_column('xp_objekt', 'rechtscharakter',
                    existing_type=postgresql.ENUM('FestsetzungBPlan', 'NachrichtlicheUebernahme', 'DarstellungFPlan',
                                                  'ZielDerRaumordnung', 'GrundsatzDerRaumordnung',
                                                  'NachrichtlicheUebernahmeZiel', 'NachrichtlicheUebernahmeGrundsatz',
                                                  'NurInformationsgehaltRPlan', 'TextlichesZielRaumordnung',
                                                  'ZielUndGrundsatzRaumordnung', 'VorschlagRaumordnung',
                                                  'FestsetzungImLP', 'GeplanteFestsetzungImLP',
                                                  'DarstellungKennzeichnungImLP',
                                                  'LandschaftsplanungsInhaltZurBeruecksichtigung', 'Hinweis',
                                                  'Kennzeichnung', 'Vermerk', 'Unbekannt', 'Sonstiges',
                                                  name='xp_rechtscharakter'),
                    nullable=False)

    op.alter_column('xp_plan', 'raeumlicherGeltungsbereich',
                    existing_type=Geometry(from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
                    nullable=False)

    op.create_check_constraint("prevent_geometry_collection", "bp_objekt",
                               "GeometryType(position) NOT IN ('GEOMETRYCOLLECTION')")
    op.create_check_constraint("prevent_geometry_collection", "fp_objekt",
                               "GeometryType(position) NOT IN ('GEOMETRYCOLLECTION')")
    op.create_check_constraint("prevent_geometry_collection", "so_objekt",
                               "GeometryType(position) NOT IN ('GEOMETRYCOLLECTION')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('fp_zweckbestimmung_versorgung', sa.Column('detail_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('bp_zweckbestimmung_gruen', sa.Column('detail_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('bp_komplexe_sondernutzung', sa.Column('detail_id', postgresql.UUID(), autoincrement=False, nullable=True))

    op.drop_table('assoc_detail_zweckgemeinbedarf')

    op.drop_constraint("prevent_geometry_collection", "bp_objekt", type_="check")
    op.drop_constraint("prevent_geometry_collection", "fp_objekt", type_="check")
    op.drop_constraint("prevent_geometry_collection", "so_objekt", type_="check")
    # ### end Alembic commands ###
