from SAGisXPlanung import XPlanVersion

XPLAN_ABSTRACT_CLASSES = {
    XPlanVersion.FIVE_THREE: {
        'XP_Plan',
        'XP_Bereich',
        'XP_Objekt',
        'XP_TextAbschnitt',
        'XP_GenerAttribut',
        'XP_AbstraktesPraesentationsobjekt',
        'XP_TPO',
        'BP_Objekt',
        'BP_Flaechenobjekt',
        'BP_Flaechenschlussobjekt',
        'BP_Geometrieobjekt',
        'BP_Linienobjekt',
        'BP_Punktobjekt',
        'BP_Ueberlagerungsobjekt',
        'FP_Objekt',
        'FP_Flaechenobjekt',
        'FP_Flaechenschlussobjekt',
        'FP_Geometrieobjekt',
        'FP_Linienobjekt',
        'FP_Punktobjekt',
        'FP_Ueberlagerungsobjekt',
        'LP_Objekt',
        'LP_Flaechenobjekt',
        'LP_Geometrieobjekt',
        'LP_Linienobjekt',
        'LP_Punktobjekt',
        'LP_SchutzobjektLandesrecht',
        'RP_Objekt',
        'RP_Geometrieobjekt',
        'SO_Objekt',
        'SO_Flaechenobjekt',
        'SO_Geometrieobjekt',
        'SO_Punktobjekt',
    },
    XPlanVersion.SIX: {
        'XP_Plan',
        'XP_Bereich',
        'XP_Objekt',
        'XP_GenerAttribut',
        'XP_AbstraktesPraesentationsobjekt',
        'XP_TPO',
        'BP_Objekt',
        'BP_Flaechenobjekt',
        'BP_Flaechenschlussobjekt',
        'BP_Geometrieobjekt',
        'BP_Linienobjekt',
        'BP_Punktobjekt',
        'BP_Ueberlagerungsobjekt',
        'FP_Objekt',
        'FP_Flaechenobjekt',
        'FP_Flaechenschlussobjekt',
        'FP_Geometrieobjekt',
        'FP_Linienobjekt',
        'FP_Punktobjekt',
        'FP_Ueberlagerungsobjekt',
        'LP_Objekt',
        'LP_Geometrieobjekt',
        'LP_Linienobjekt',
        'LP_Punktobjekt',
        'RP_Objekt',
        'RP_Geometrieobjekt',
        'SO_Objekt',
        'SO_Flaechenobjekt',
        'SO_Geometrieobjekt',
        'SO_Punktobjekt',
    },
}


def is_abstract_in_version(cls, version: XPlanVersion) -> bool:
    """Check if a class is abstract in the given XPlan version."""
    return cls.__name__ in XPLAN_ABSTRACT_CLASSES.get(version, set())
