
from .enums import SO_KlassifizSchutzgebietWasserrecht, SO_SchutzzonenWasserrecht, SO_KlassifizSchutzgebietSonstRecht
from .feature_types import SO_SchutzgebietWasserrecht, SO_SchutzgebietSonstigesRecht
