# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: SAGis XPlanung Dokumentation
site_url: https://mydomain.org/
theme:
  name: material
  language: de
  features:
    - search.suggest
    - search.highlight
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tooltips
  font:
    text: Overpass
  logo: assets/NTI_primary.png
  palette:
    # Palette toggle for light mode
    - scheme: nti
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/nti.css
extra:
  homepage: https://nti-group.com/de
  tags:
    Vollversion: full
  social:
    - icon: material/email
      link: mailto:qgis-de@nti.biz
    - icon: material/github
      link: https://github.com/nti-de/SAGisXPlanung
    - icon: simple/qgis
      link: https://github.com/nti-de/SAGisXPlanung

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - zensical.extensions.glightbox:
      auto: false

plugins:
  - tags
  - search
  - offline

nav:
  - Start: index.md
  - Installation:
      - Installation und Einrichtung:
        - setup/index.md
        - Installation: setup/install.md
        - Einrichtung einer Datenquelle: setup/database-setup.md
        - Update einer Installation: setup/update.md
  - Dokumentation:
    - Anwendungsfälle:
        - new-plan.md
        - map-display.md
        - add-plancontent.md
        - plan-import.md
        - plan-export.md
        - multi-edit.md
        - text-contents.md
    - Elemente der Oberfläche:
        - elements/main-dialog.md
        - elements/plan-details.md
        - elements/plan-overview.md
    - Einstellungen:
        - settings/index.md
        - Allgemein: settings/general.md
        - Formulare: settings/forms.md
        - Datenbank: settings/database.md
        - Codelisten: settings/codelists.md
        - Darstellung: settings/symbology.md
  - Projekt:
      - Changelog:
          - changelog/index.md
          - Version 2.14.0: changelog/v214.md
      - Allgemeines:
          - Kontakt & Support: general/support.md
          - FAQ: general/FAQ.md
      - Integrationen:
          - XPlanung24: integrations/xplanung24.md
copyright: Copyright &copy; 2026 NTI Deutschland GmbH