name: Tests

on:
  push:
    branches:
      - master
      - ce
      - lite

  pull_request:
    branches:
      - master
      - ce
      - lite

  workflow_dispatch:

jobs:
  commit-sha:
    name: Get Commit Hash
    runs-on: ubuntu-latest

    outputs:
      commit_sha: ${{steps.get_hash.outputs.COMMIT_SHA}}

    steps:
    - name: Checkout Project
      uses: actions/checkout@v4

    - name: commit sha
      id: get_hash
      run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  test:
    name: Test on ${{matrix.container }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: ['qgis/qgis:latest', 'qgis/qgis:ltr-jammy']

    container:
      image: ${{ matrix.container }}
      options: --user 0:0

    steps:
    
    - name: Checkout Project
      uses: actions/checkout@v4

    - name: Install sudo
      run: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo
        
    - name: Install dependencies
      run: |
        set -e
        sudo apt install -y build-essential
        
        if python3 -m pip help install | grep -q break-system-packages; then
            PIP_BREAK="--break-system-packages --ignore-installed"
        else
            PIP_BREAK=""
        fi
        
        python3 -m pip install $PIP_BREAK --upgrade pip
        python3 -m pip install $PIP_BREAK --upgrade setuptools
        sudo apt-get install -y libgeos-dev python3-mock
        
        pip install $PIP_BREAK \
            pytest \
            pytest-azurepipelines \
            pytest-cov \
            pytest-qt \
            pytest-mock \
            pytest-asyncio \
            pytest-qgis \
            nest-asyncio
        
        pip install $PIP_BREAK -r requirements.txt
        
    - name: Unit Tests
      env:
        DISPLAY: :99
        QT_QPA_PLATFORM: "offscreen"
      run: |
        python3 -m pytest --cache-clear --cov=src --cov-report=xml

  alembic-revision:
    name: Generate SQL Scripts
    needs: [test, commit-sha]
    runs-on: ubuntu-latest

    container: 'qgis/qgis:release-3_28'

    steps:
    - name: Checkout Project
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install alembic alembic-postgresql-enum

    - name: Parse Alembic History
      id: alembic_history
      run: |
        prev_revision=`alembic history | head -n1 | awk '{print $1}'`
        revision_tag=`alembic history | head -n1 | awk '{print $NF}'`
        prev_tag=`alembic history | head -n2 | tail -n1 | awk '{print $NF}'`

        echo "prev_revision=$prev_revision" >> $GITHUB_OUTPUT
        echo "revision_tag=$revision_tag" >> $GITHUB_OUTPUT
        echo "prev_tag=$prev_tag" >> $GITHUB_OUTPUT 

    - name: Generate Revisions
      run: |
        alembic upgrade head --sql > create_${{steps.alembic_history.outputs.revision_tag}}.sql
        alembic downgrade head:${{steps.alembic_history.outputs.prev_revision}} --sql > downgrade_to_${{steps.alembic_history.outputs.prev_tag}}.sql
        alembic upgrade ${{steps.alembic_history.outputs.prev_revision}}:head --sql > upgrade_from_${{steps.alembic_history.outputs.prev_tag}}.sql

    - name: Upload SQL Scripts
      if: ${{ !env.ACT }} # skip during local actions testing
      uses: actions/upload-artifact@v4
      with:
        name: SAGis.XPlanung.sql-scripts@${{ needs.commit-sha.outputs.commit_sha }}
        path: '*.sql'
