pool:
  vmImage: ubuntu-latest

trigger:
 tags:
   include:
     - v2.*

steps:

- script: |
    python3 -m pip install --upgrade pip
    python3 -m pip install mkdocs-material
  displayName: 'Install mkdocs'

- script: |
    python3 -m mkdocs build
  displayName: 'Build Documentation with mkdocs'
  workingDirectory: docs

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/docs/site'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/src/SAGisXPlanung/docs'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'src/SAGisXPlanung'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/SAGisXPlanung_$(Build.SourceBranchName).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
